# NumPy for Data Science
NumPy (Numerical Python) is the foundation of the Python data-science stack. Pandas, Matplotlib and
scikit-learn are all built on top of NumPy arrays. This notebook covers everything I used from NumPy
during the DSML course, in the order I learned it.

**Contents**
1. Creating arrays
2. Array attributes (shape, ndim, dtype, size)
3. Indexing & slicing
4. Vectorised arithmetic & broadcasting
5. Aggregations / descriptive statistics
6. Reshaping, stacking & splitting
7. Boolean masking & filtering
8. Random numbers (used for synthetic datasets)
9. Linear algebra basics
10. Handling missing values (`np.nan`)
11. Loading a real dataset with NumPy (Iris)
12. Why NumPy is faster than Python lists

**Dataset used:** `datasets/iris_data.csv` (150 flowers, 4 measurements, 3 species)

In [1]:
import numpy as np
print('NumPy version:', np.__version__)

NumPy version: 2.4.2


## 1. Creating arrays

In [2]:
lst = [1, 2, 3, 4, 5]
arr = np.array(lst)          # from a Python list
print(arr, type(arr))

matrix = np.array([[1, 2], [3, 4]])   # 2-D array
print(matrix)

[1 2 3 4 5] <class 'numpy.ndarray'>
[[1 2]
 [3 4]]


In [3]:
print(np.zeros(5))             # array of zeros
print(np.ones((2, 3)))         # 2x3 array of ones
print(np.full((2, 2), 7))      # filled with a constant
print(np.eye(3))               # identity matrix
print(np.arange(0, 10, 2))     # like range() -> [0 2 4 6 8]
print(np.linspace(0, 1, 5))    # 5 evenly spaced numbers from 0 to 1

[0. 0. 0. 0. 0.]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


## 2. Array attributes

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])
print('shape :', a.shape)   # (rows, cols)
print('ndim  :', a.ndim)    # number of dimensions
print('size  :', a.size)    # total elements
print('dtype :', a.dtype)   # data type of elements

shape : (2, 3)
ndim  : 2
size  : 6
dtype : int64


In [5]:
# Changing the data type
f = a.astype(float)
print(f, f.dtype)

[[1. 2. 3.]
 [4. 5. 6.]] float64


## 3. Indexing & slicing

In [6]:
arr = np.arange(10, 20)
print(arr)
print('first      :', arr[0])
print('last       :', arr[-1])
print('2 to 5     :', arr[2:6])
print('every 2nd  :', arr[::2])
print('reversed   :', arr[::-1])

[10 11 12 13 14 15 16 17 18 19]
first      : 10
last       : 19
2 to 5     : [12 13 14 15]
every 2nd  : [10 12 14 16 18]
reversed   : [19 18 17 16 15 14 13 12 11 10]


In [7]:
m = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print('row 0      :', m[0])
print('column 1   :', m[:, 1])
print('element 1,2:', m[1, 2])
print('sub-matrix :\n', m[0:2, 1:3])

row 0      : [1 2 3]
column 1   : [2 5 8]
element 1,2: 6
sub-matrix :
 [[2 3]
 [5 6]]


## 4. Vectorised arithmetic & broadcasting
Operations apply element-wise without writing loops.

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print('a + b =', a + b)
print('a - b =', a - b)
print('a * b =', a * b)
print('a / b =', a / b)
print('a ** 2 =', a ** 2)
print('a * 2 =', a * 2)      # scalar broadcast

a + b = [5 7 9]
a - b = [-3 -3 -3]
a * b = [ 4 10 18]
a / b = [0.25 0.4  0.5 ]
a ** 2 = [1 4 9]
a * 2 = [2 4 6]


In [9]:
# Broadcasting: a (3,3) matrix + a (3,) row vector
m = np.ones((3, 3))
row = np.array([10, 20, 30])
print(m + row)

[[11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]]


In [10]:
# Universal functions (ufuncs)
x = np.array([1, 4, 9, 16])
print('sqrt :', np.sqrt(x))
print('log  :', np.log(x))
print('exp  :', np.exp([0, 1, 2]))

sqrt : [1. 2. 3. 4.]
log  : [0.         1.38629436 2.19722458 2.77258872]
exp  : [1.         2.71828183 7.3890561 ]


## 5. Aggregations / descriptive statistics

In [11]:
marks = np.array([35, 40, 48, 52, 61, 65, 70, 78, 82, 90])
print('sum    :', marks.sum())
print('mean   :', marks.mean())
print('median :', np.median(marks))
print('std    :', marks.std())
print('var    :', marks.var())
print('min/max:', marks.min(), marks.max())
print('argmax :', marks.argmax(), '(index of the highest mark)')
print('25th, 75th percentile:', np.percentile(marks, [25, 75]))

sum    : 621
mean   : 62.1
median : 63.0
std    : 17.386489007272285
var    : 302.29
min/max: 35 90
argmax : 9 (index of the highest mark)
25th, 75th percentile: [49. 76.]


In [12]:
# Axis-wise aggregation on a 2-D array
scores = np.array([[80, 90, 70],
                   [60, 75, 85]])
print('column means (axis=0):', scores.mean(axis=0))
print('row means    (axis=1):', scores.mean(axis=1))

column means (axis=0): [70.  82.5 77.5]
row means    (axis=1): [80.         73.33333333]


## 6. Reshaping, stacking & splitting

In [13]:
a = np.arange(1, 13)
print(a.reshape(3, 4))
print(a.reshape(2, -1))       # -1 lets NumPy work out the size
print(a.reshape(3, 4).T)      # transpose
print(a.reshape(3, 4).flatten())

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [14]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print('vstack:\n', np.vstack([x, y]))
print('hstack:', np.hstack([x, y]))
print('split :', np.split(np.arange(9), 3))

vstack:
 [[1 2 3]
 [4 5 6]]
hstack: [1 2 3 4 5 6]
split : [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


In [15]:
# scikit-learn expects a 2-D feature matrix -> reshape(-1, 1)
hours = np.array([1, 2, 3, 4, 5])
print(hours.shape, '->', hours.reshape(-1, 1).shape)

(5,) -> (5, 1)


## 7. Boolean masking & filtering

In [16]:
marks = np.array([35, 40, 48, 52, 61, 65, 70, 78, 82, 90])
passed = marks >= 50
print(passed)
print('passed marks :', marks[passed])
print('count passed :', passed.sum())
print('between 50-80:', marks[(marks >= 50) & (marks <= 80)])
print('grade        :', np.where(marks >= 50, 'Pass', 'Fail'))

[False False False  True  True  True  True  True  True  True]
passed marks : [52 61 65 70 78 82 90]
count passed : 7
between 50-80: [52 61 65 70 78]
grade        : ['Fail' 'Fail' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass' 'Pass']


## 8. Random numbers
These are used in `03_Statistics/Descriptive_Statistics.ipynb` to generate a synthetic customer dataset.

In [17]:
rng = np.random.default_rng(42)          # seeded -> reproducible
print('ints   :', rng.integers(18, 61, 5))            # like np.random.randint
print('normal :', rng.normal(55000, 15000, 3).round())
print('poisson:', rng.poisson(5, 5))
print('uniform:', rng.uniform(0, 1, 3))
print('choice :', rng.choice(['A', 'B', 'C'], 5))

ints   : [21 51 46 36 36]
normal : [69108. 25734. 35467.]
poisson: [7 3 9 6 3]
uniform: [0.66981399 0.43715192 0.8326782 ]
choice : ['C' 'B' 'C' 'A' 'A']


In [18]:
# Legacy API used in class
np.random.seed(0)
income = np.random.normal(55000, 15000, 10).clip(20000, 120000)
print(income.round())

[81461. 61002. 69681. 88613. 83013. 40341. 69251. 52730. 53452. 61159.]


## 9. Linear algebra basics
Linear regression (covered later in `05_Linear_Regression`) is built on these operations.

In [19]:
A = np.array([[2, 1], [1, 3]])
B = np.array([[1, 0], [0, 1]])
print('A @ B        :\n', A @ B)          # matrix multiplication
print('dot product  :', np.dot([1, 2, 3], [4, 5, 6]))
print('determinant  :', np.linalg.det(A))
print('inverse      :\n', np.linalg.inv(A))

A @ B        :
 [[2 1]
 [1 3]]
dot product  : 32
determinant  : 5.000000000000001
inverse      :
 [[ 0.6 -0.2]
 [-0.2  0.4]]


In [20]:
# Solving linear regression by hand with the Normal Equation: theta = (X^T X)^-1 X^T y
hours = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
marks = np.array([35, 40, 48, 52, 61, 65, 70, 78, 82, 90])
X = np.c_[np.ones(len(hours)), hours]       # add bias column
theta = np.linalg.inv(X.T @ X) @ X.T @ marks
print(f'intercept = {theta[0]:.2f}, slope = {theta[1]:.2f}')
print('predicted marks for 11 hours:', round(theta[0] + theta[1] * 11, 2))

intercept = 28.87, slope = 6.04


predicted marks for 11 hours: 95.33


## 10. Handling missing values

In [21]:
data = np.array([4.0, np.nan, 7.0, 10.0, np.nan])
print('isnan   :', np.isnan(data))
print('mean    :', np.mean(data), '<- nan poisons normal functions')
print('nanmean :', np.nanmean(data))
filled = np.where(np.isnan(data), np.nanmean(data), data)
print('filled  :', filled)

isnan   : [False  True False False  True]
mean    : nan <- nan poisons normal functions
nanmean : 7.0
filled  : [ 4.  7.  7. 10.  7.]


## 11. Loading a real dataset with NumPy
NumPy can read numeric CSV data directly. Here it loads the Iris dataset without Pandas.

In [22]:
features = np.genfromtxt('datasets/iris_data.csv', delimiter=',', skip_header=1, usecols=(1, 2, 3, 4))
species = np.genfromtxt('datasets/iris_data.csv', delimiter=',', skip_header=1, usecols=5, dtype=str)
names = ['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth']
print('features:', features.shape, features.dtype, '| species:', species.shape)
print(features[:5])
print(np.unique(species, return_counts=True))

features: (150, 4) float64 | species: (150,)
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='<U15'), array([50, 50, 50]))


In [23]:
# Column-wise statistics (axis=0)
for name, mean, std, lo, hi in zip(names, features.mean(axis=0), features.std(axis=0),
                                   features.min(axis=0), features.max(axis=0)):
    print(f'{name:12s} mean={mean:.2f}  std={std:.2f}  min={lo}  max={hi}')

SepalLength  mean=5.84  std=0.83  min=4.3  max=7.9
SepalWidth   mean=3.05  std=0.43  min=2.0  max=4.4
PetalLength  mean=3.76  std=1.76  min=1.0  max=6.9
PetalWidth   mean=1.20  std=0.76  min=0.1  max=2.5


In [24]:
# Boolean masks on a second array: average measurements per species
for sp in np.unique(species):
    print(f'{sp:16s}', features[species == sp].mean(axis=0).round(2))

Iris-setosa      [5.01 3.42 1.46 0.24]
Iris-versicolor  [5.94 2.77 4.26 1.33]
Iris-virginica   [6.59 2.97 5.55 2.03]


In [25]:
# Which flowers have petals longer than 6 cm?
long_petals = features[:, 2] > 6
print(long_petals.sum(), 'flowers:', np.unique(species[long_petals]))

9 flowers: ['Iris-virginica']


In [26]:
# Correlation matrix between the 4 measurements
print(np.corrcoef(features, rowvar=False).round(2))

[[ 1.   -0.11  0.87  0.82]
 [-0.11  1.   -0.42 -0.36]
 [ 0.87 -0.42  1.    0.96]
 [ 0.82 -0.36  0.96  1.  ]]


In [27]:
# Feature scaling, which many ML models need
z_scores = (features - features.mean(axis=0)) / features.std(axis=0)          # standardisation
min_max = (features - features.min(axis=0)) / np.ptp(features, axis=0)        # normalisation to [0, 1]
print('standardised mean ~0 :', z_scores.mean(axis=0).round(6))
print('standardised std  = 1:', z_scores.std(axis=0).round(6))
print('min-max range        :', min_max.min(axis=0), min_max.max(axis=0))

standardised mean ~0 : [-0. -0. -0. -0.]
standardised std  = 1: [1. 1. 1. 1.]
min-max range        : [0. 0. 0. 0.] [1. 1. 1. 1.]


## 12. Why NumPy? Speed comparison

In [28]:
import time
n = 1_000_000
py_list = list(range(n))
np_arr = np.arange(n)

t = time.perf_counter(); [x * 2 for x in py_list]; t_list = time.perf_counter() - t
t = time.perf_counter(); np_arr * 2;              t_np = time.perf_counter() - t
print(f'Python list: {t_list*1000:.1f} ms | NumPy: {t_np*1000:.1f} ms | ~{t_list/t_np:.0f}x faster')

Python list: 54.2 ms | NumPy: 2.1 ms | ~26x faster


## Key takeaways
- NumPy arrays are homogeneous, fixed-type and stored contiguously, which makes them fast.
- Vectorisation and broadcasting replace most `for` loops.
- `axis=0` works down columns and `axis=1` works across rows.
- Boolean masks are the basis of filtering in Pandas too.
- ML libraries expect 2-D feature arrays of shape `(n_samples, n_features)`.
- `np.genfromtxt` loads numeric CSVs, but mixed-type tables are easier in Pandas (next folder).